name: Release (dev)
on: [pull_request]

jobs:

    fix:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/actions/setup

            - name: Fix
              run: pnpm run fix
              
    release:
        runs-on: ubuntu-latest
        needs: fix

        steps:
            - uses: actions/checkout@v4

            - uses: ./.github/actions/setup

            - run: pnpm run ci:publish-dev
